# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2025.01.22-24-g5465c47
_src_path: gh:scientific-python/cookie
backend: hatch
email: rcaddy@princeton.edu
full_name: Robert Caddy
license: MIT
org: PegasusPIC
project_name: pegasustools
project_short_description: Analysis package for the Pegasus PIC code.
url: https://github.com/PegasusPIC/pegasustools
vcs: true
